### ISSUE TITLE
Getting error while installing Bcrypt with visual studio 2015 community

### ISSUE THREAD

**Issue by kiiiiNNNNNNNNNyyyy** [colincoghill/oasisqe#78]
While Installing brcrypt on my system, I am getting this error. I have already installed Visual Studio Community 2015 and Open SSL.

`PS C:\Users\Arjun\desktop\node\UDEMY PROJECT> cd .\Nodeauth
PS C:\Users\Arjun\desktop\node\UDEMY PROJECT\Nodeauth> npm config set msvs_version 2015 --global
PS C:\Users\Arjun\desktop\node\UDEMY PROJECT\Nodeauth> npm install bcrypt

> bcrypt@0.8.5 install C:\Users\Arjun\desktop\node\UDEMY PROJECT\Nodeauth\node_modules\bcrypt
> node-gyp rebuild

C:\Users\Arjun\desktop\node\UDEMY PROJECT\Nodeauth\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Prog
ram Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node
rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  blowfish.cc
  bcrypt.cc
  bcrypt_node.cc
..\src\blowfish.cc(47): fatal error C1083: Cannot open include file: 'sys/types.h': No such file or directory [C:\Users
\Arjun\desktop\node\UDEMY PROJECT\Nodeauth\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
..\src\bcrypt.cc(48): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory [C:\Users\Arjun
\desktop\node\UDEMY PROJECT\Nodeauth\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
c:\users\arjun.node-gyp\5.0.0\include\node\uv-errno.h(25): fatal error C1083: Cannot open include file: 'errno.h': No
such file or directory (compiling source file ..\src\bcrypt_node.cc) [C:\Users\Arjun\desktop\node\UDEMY PROJECT\Nodeaut
h\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
70:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Arjun\desktop\node\UDEMY PROJECT\Nodeauth\node_modules\bcrypt
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "ins
tall" "bcrypt"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Arjun\desktop\node\UDEMY PROJECT\Nodeauth\npm-debug.log
PS C:\Users\Arjun\desktop\node\UDEMY PROJECT\Nodeauth>

`

I am not familiar with visual studio. Please help me.

**Comment by kiiiiNNNNNNNNNyyyy** [comment]
Installed bcryptjs instead
